chore(analysis): remove sonar job

diff --git a/.github/workflows/analysis.yaml b/.github/workflows/analysis.yaml
--- a/.github/workflows/analysis.yaml
+++ b/.github/workflows/analysis.yaml
@@ -18,30 +18,6 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  tests:
-    name: Tests
-    if: ${{ ! github.event.pull_request.draft }}
-    runs-on: ubuntu-22.04
-    timeout-minutes: 5
-      strategy:
-        matrix:
-          dir: [dags]
-          include:
-            - dir: dags
-              token: SONAR_TOKEN
-      steps:
-        - uses: bcgov-nr/action-test-and-analyse@v1.1.1
-            dir: ${{ matrix.dir }}
-            node_version: "20"
-            sonar_args: >
-              -Dsonar.exclusions=**/coverage/**,**/node_modules/**,**/*spec.ts
-              -Dsonar.organization=bcgov-sonarcloud
-              -Dsonar.projectKey=quickstart-openshift_${{ matrix.dir }}
-              -Dsonar.sources=src
-              -Dsonar.python.lcov.reportPaths=./coverage/lcov.info
-            sonar_token: ${{ secrets[matrix.token] }}
-            triggers: ('${{ matrix.dir }}/')
-
   codeql:
     name: CodeQL Security Scan
     if: ${{ ! github.event.pull_request.draft }}
@@ -58,36 +34,34 @@ jobs:
         with:
           category: "/language:python"  
   
-    # https://github.com/marketplace/actions/aqua-security-trivy
-    trivy:
-      name: Trivy Security Scan
-      if: ${{ ! github.event.pull_request.draft }}
-      runs-on: ubuntu-24.04
-      timeout-minutes: 5
-      steps:
-        - uses: actions/checkout@v4
-        - name: Run Trivy vulnerability scanner in repo mode
-          uses: aquasecurity/trivy-action@0.30.0
-          with:
-            format: "sarif"
-            output: "trivy-results.sarif"
-            ignore-unfixed: true
-            scan-type: "fs"
-            languages: "python"
-            scanners: "vuln,secret,config"
-            severity: "CRITICAL,HIGH"
-
-        - name: Upload Trivy scan results to GitHub Security tab
-          uses: github/codeql-action/upload-sarif@v3
-          with:
-            sarif_file: "trivy-results.sarif"
-
-    results:
-      name: Analysis Results
-      needs: [trivy]
-      if: always()
-      runs-on: ubuntu-24.04
-      steps:
-        - if: contains(needs.*.result, 'failure')
-          run: echo "At least one job has failed." && exit 1
-        - run: echo "Success!"
+  # https://github.com/marketplace/actions/aqua-security-trivy
+  trivy:
+    name: Trivy Security Scan
+    if: ${{ ! github.event.pull_request.draft }}
+    runs-on: ubuntu-24.04
+    timeout-minutes: 5
+    steps:
+      - uses: actions/checkout@v4
+      - name: Run Trivy vulnerability scanner in repo mode
+        uses: aquasecurity/trivy-action@0.30.0
+        with:
+          format: "sarif"
+          output: "trivy-results.sarif"
+          ignore-unfixed: true
+          scan-type: "fs"
+          languages: "python"
+          scanners: "vuln,secret,config"
+          severity: "CRITICAL,HIGH"
+      - name: Upload Trivy scan results to GitHub Security tab
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: "trivy-results.sarif"
+  results:
+    name: Analysis Results
+    needs: [trivy]
+    if: always()
+    runs-on: ubuntu-24.04
+    steps:
+      - if: contains(needs.*.result, 'failure')
+        run: echo "At least one job has failed." && exit 1
+      - run: echo "Success!"
